DROP TABLE IF EXISTS player_playing_time;
CREATE TABLE player_playing_time (
  id int NOT NULL,
  player varchar(50) DEFAULT NULL,
  position varchar(50) DEFAULT NULL,
  team varchar(50) DEFAULT NULL,
  age varchar(50) DEFAULT NULL,
  birth_year int DEFAULT NULL,
  games int DEFAULT NULL,
  minutes int DEFAULT NULL,
  minutes_per_game int DEFAULT NULL,
  minutes_pct DOUBLE PRECISION  DEFAULT NULL,
  minutes_90s DOUBLE PRECISION  DEFAULT NULL,
  games_starts int DEFAULT NULL,
  minutes_per_start int DEFAULT NULL,
  games_complete int DEFAULT NULL,
  games_subs int DEFAULT NULL,
  minutes_per_sub int DEFAULT NULL,
  unused_subs int DEFAULT NULL,
  points_per_game DOUBLE PRECISION  DEFAULT NULL,
  on_goals_for int DEFAULT NULL,
  on_goals_against int DEFAULT NULL,
  plus_minus int DEFAULT NULL,
  plus_minus_per90 DOUBLE PRECISION  DEFAULT NULL,
  plus_minus_wowy DOUBLE PRECISION  DEFAULT NULL,
  on_xg_for DOUBLE PRECISION  DEFAULT NULL,
  on_xg_against DOUBLE PRECISION  DEFAULT NULL,
  xg_plus_minus DOUBLE PRECISION  DEFAULT NULL,
  xg_plus_minus_per90 DOUBLE PRECISION  DEFAULT NULL,
  xg_plus_minus_wowy DOUBLE PRECISION  DEFAULT NULL,
  PRIMARY KEY (id)
) ;